package com.myspace.test01;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Item Id")
	private java.lang.String itemId;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "Price")
	private double price;

	public Product() {
	}

	public java.lang.String getItemId() {
		return this.itemId;
	}

	public void setItemId(java.lang.String itemId) {
		this.itemId = itemId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Product(java.lang.String itemId, java.lang.String name,
			java.lang.String description, double price) {
		this.itemId = itemId;
		this.name = name;
		this.description = description;
		this.price = price;
	}

}