spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: spring-boot-db-credentials
              key: database.user
        - name: SPRING_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-boot-db-credentials
              key: database.password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20